### ISSUE TITLE
D3D10 and D3D11 support?

### ISSUE THREAD

**Issue by tcharchar** [NVIDIAGameWorks/dxvk-remix#62]
I am aware that this is most likely the intended behavior, given how many header files both of them require, whom are missing from this repository.

Despite that, it would be nice if support past dx9 was documented/mentioned anywhere, since I've attempted compiling this for dx11 with no success whatsoever.

**Comment by anon-apple** [comment]
There is not really support past DirectX 9. DirectX 10 [removed fixed function](https://learn.microsoft.com/en-us/windows/win32/direct3d10/d3d10-graphics-programming-guide-d3d9-to-d3d10-considerations?redirectedfrom=MSDN#removal-of-fixed-function) which is required for Remix to work, it was only in DX 9 really for compatibility purposes anyways (since it originated from DX 7).
In addition, games even around DX 9 times and especially later on once Fixed Function was removed rely more on shaders which makes it essentially impractical to extract the information Remix needs about the game through API calls (e.g. camera matrices, light properties, geometry information, skeletal animation information, material textures). This is also why Remix works best with games designed more around a DirectX 8 era of behavior, as the more they use shaders even in DirectX 9 the harder it gets to deal with them.
It's in theory possible to extract this information with a lot of per-game effort (essentially hijacking the buffers and data given to shaders and parsing it in a way specific to that game based on known layouts of information) but that is a lot more complicated than how Remix works currently.

**Comment by MarkEHenderson** [comment]
Docs for compatibility are available here:
https://docs.omniverse.nvidia.com/kit/docs/rtx_remix/latest/docs/remix-overview.html#compatibility

**Comment by useranon350** [comment]
Would it be possible to solve the shader limitations by hijacking shader compilation?
